<?php
// Do not edit this file. Generated by admin script.
// Booklibrary Configuration file
// General Informations 
$booklibrary_configuration['release']['version']='3.1 Free';
$booklibrary_configuration['release']['date']='23 December 2015';
// edit book 
$booklibrary_configuration['editbook']['check']['isbn']='1';
$booklibrary_configuration['editbook']['default']['host']='1';
$booklibrary_configuration['editbook']['default']['lang']='English';
// price settings
$booklibrary_configuration['price']['show']='0';
$booklibrary_configuration['price']['registrationlevel']='0';
// amazon settings
$booklibrary_configuration['ws']['amazon']['tag']='orda-20';
$booklibrary_configuration['ws']['amazon']['devtag']= 'AKIAIWZKHN3I6UWTN3XQ';
$booklibrary_configuration['ws']['amazon']['secret_key']= '';
// auto increment for bookid, if 1 - can't add random bookid 
$booklibrary_configuration['bookid']['auto-increment']['boolean']='1';
// fetch images settings
$booklibrary_configuration['fetchImages']['boolean']='1';
$booklibrary_configuration['fetchImages']['location']='/components/com_booklibrary/covers/';
// review settings
$booklibrary_configuration['reviews']['show']='1';
$booklibrary_configuration['reviews']['registrationlevel']='-2';
// publish added book
$booklibrary_configuration['publish_on_add']['show']='';
$booklibrary_configuration['publish_on_add']['registrationlevel']='0';
$booklibrary_configuration['litpage']['show']='0';
$booklibrary_configuration['litpage']['registrationlevel']='0';
// lend settings
$booklibrary_configuration['lendstatus']['show']='1';
$booklibrary_configuration['lendrequest']['registrationlevel']='-2';
// ebook settings
$booklibrary_configuration['ebooks']['allow']='1';
$booklibrary_configuration['ebooks']['show']='1';
$booklibrary_configuration['ebooks']['registrationlevel']='-2';
$booklibrary_configuration['ebooks']['location']='/components/com_booklibrary/ebooks/';
// debuging
$booklibrary_configuration['debug']='';
$booklibrary_configuration['page']['items']='10';
$booklibrary_configuration['category']['default_sort']='';
// foto size
$booklibrary_configuration['foto']['high']= '160';
$booklibrary_configuration['foto']['width']= '124';
$booklibrary_configuration['license']['show']='';
$booklibrary_configuration['license']['text']= '';
// show cb_mybook
$booklibrary_configuration['cb_mybook']['show']='0';
$booklibrary_configuration['cb_mybook']['registrationlevel']='0';
// show cb_edit
$booklibrary_configuration['cb_edit']['show']='0';
$booklibrary_configuration['cb_edit']['registrationlevel']='0';
// show cb_rent
$booklibrary_configuration['cb_rent']['show']='0';
$booklibrary_configuration['cb_rent']['registrationlevel']='0';
// show cb_history
$booklibrary_configuration['cb_history']['show']='0';
$booklibrary_configuration['cb_history']['registrationlevel']='0';
// button '[ buy now ]'
$booklibrary_configuration['buy_now']['show']='1';
$booklibrary_configuration['buy_now']['allow']['categories']='-2';
$booklibrary_configuration['addbook_button']['show']='0';
$booklibrary_configuration['addbook_button']['allow']['categories']='0';
$booklibrary_configuration['addbook_button']['allow']['registrationlevel']='0';
$booklibrary_configuration['update']='1';
$booklibrary_configuration['approve_on_add']['show']='';
$booklibrary_configuration['approve_on_add']['registrationlevel']='0';
// button '[ my_books_button ]'
$booklibrary_configuration['my_books_button']['show']='0';
$booklibrary_configuration['my_books_button']['registrationlevel']='0';
// Advance search 
$booklibrary_configuration['advsearch']['show']='0';
$booklibrary_configuration['advsearch']['registrationlevel']='0';
$booklibrary_configuration['search_field']['show']='0';
$booklibrary_configuration['search_field']['registrationlevel']='0';
//merge description 
$booklibrary_configuration['merge_description']['use']='1';
$booklibrary_configuration['merge_description']['registrationlevel']='-2';
$booklibrary_configuration['rss']['show']='0';
$booklibrary_configuration['rss']['registrationlevel']='0';
$booklibrary_configuration['ownerslist']['show']='';
$booklibrary_configuration['ownerslist']['registrationlevel']='0';
$booklibrary_configuration['print_view']['show']='0';
$booklibrary_configuration['print_view']['registrationlevel']='0';
$booklibrary_configuration['print_pdf']['show']='0';
$booklibrary_configuration['print_pdf']['registrationlevel']='0';
$booklibrary_configuration['mail_to']['show']='0';
$booklibrary_configuration['mail_to']['registrationlevel']='0';
// send email for admin
$booklibrary_configuration['review_email']['address']='';
$booklibrary_configuration['review_added_email']['show']='0';
$booklibrary_configuration['review_added_email']['registrationlevel']='0';
$booklibrary_configuration['suggest_email']['address']='';
$booklibrary_configuration['suggest_added_email']['show']='0';
$booklibrary_configuration['suggest_added_email']['registrationlevel']='0';
$booklibrary_configuration['lendrequest_email']['address']='';
$booklibrary_configuration['lendrequest_email']['show']='0';
$booklibrary_configuration['lendrequest_email']['registrationlevel']='0';
$booklibrary_configuration['addbook_email']['address']='';
$booklibrary_configuration['addbook_email']['show']='0';
$booklibrary_configuration['addbook_email']['registrationlevel']='0';
// show in category picture
$booklibrary_configuration['cat_pic']['show']='1';
$booklibrary_configuration['lend_answer']='0';
$booklibrary_configuration['lend_form']='';
// show subcategory
$booklibrary_configuration['subcategory']['show']='1';
//all_category 
$booklibrary_configuration['all_categories']='default';
//all_category 
$booklibrary_configuration['view_book']='';
//search_lay 
$booklibrary_configuration['search_lay']='default';
//view type 
$booklibrary_configuration['view_type']='default';
//books 
$booklibrary_configuration['books']='';
//ownerslist_page 
$booklibrary_configuration['ownerslist_page']='';
$booklibrary_configuration['proxy_server']['address']='';
$booklibrary_configuration['port_proxy_server']['address']='';
$booklibrary_configuration['login_proxy_server']['address']='';
$booklibrary_configuration['password_proxy_server']['address']='';
$booklibrary_configuration['owner']['show']='';
$booklibrary_configuration['lend_before_end_notify']='0';
$booklibrary_configuration['lend_before_end_notify_days']='2';
$booklibrary_configuration['lend_before_end_notify_email']='';
$booklibrary_configuration['price_format']=',';
// 1 - affter 0 - beffore
$booklibrary_configuration['price_unit_show']='0';
$booklibrary_configuration['date_format']='%m-%d-%Y';
$booklibrary_configuration['datetime_format']='';
$booklibrary_configuration['allowed_exts']='zip,pdf';
$booklibrary_configuration['allowed_exts_img']='jpeg,jpg,png,gif';
$booklibrary_configuration['approve_review']['show']='1';
$booklibrary_configuration['approve_review']['registrationlevel']='0';
