<?php
if (!defined('_VALID_MOS') && !defined('_JEXEC')) die('Direct Access to ' . basename(__FILE__) . ' is not allowed.');
/**
 *
 * @package BookLibrary
 * @copyright Andrey Kvasnevskiy-OrdaSoft(akbet@mail.ru); Rob de Cleen(rob@decleen.com);
 * Homepage: http://www.ordasoft.com
 * @version: 3.0 Free
 * @license GNU General Public license version 2 or later; see LICENSE.txt
 *
 */
class mosBooklibraryOthers {
    /**
     * Sets the parametes for connecting to a webservice via a
     * @param the array of parameters
     * @deprecated $Revision: 1.0 $ - December 2007
     */
    static function setParams() {
        global $booklibrary_configuration;
        // Prepare settings
        // Using single quotes is easier because you don't have to escape them. For every setting, add a line.
        $settings = "<?php\n";
        $settings.= "// Do not edit this file. Generated by admin script.\n";
        $settings.= "// Booklibrary Configuration file\n";
        $settings.= "// General Informations \n";
        $settings.= "\$booklibrary_configuration['release']['version']='" . $booklibrary_configuration['release']['version'] . "';\n";
        $settings.= "\$booklibrary_configuration['release']['date']='" . $booklibrary_configuration['release']['date'] . "';\n";
        $settings.= "// edit book \n";
        $settings.= "\$booklibrary_configuration['editbook']['check']['isbn']='" . $booklibrary_configuration['editbook']['check']['isbn'] . "';\n";
        $settings.= "\$booklibrary_configuration['editbook']['default']['host']='" . $booklibrary_configuration['editbook']['default']['host'] . "';\n";
        $settings.= "\$booklibrary_configuration['editbook']['default']['lang']='" . $booklibrary_configuration['editbook']['default']['lang'] . "';\n";
        $settings.= "// price settings\n";
        $settings.= "\$booklibrary_configuration['price']['show']='" . $booklibrary_configuration['price']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['price']['registrationlevel']='" . $booklibrary_configuration['price']['registrationlevel'] . "';\n"; // +17.01
        $settings.= "// amazon settings\n";
        $settings.= "\$booklibrary_configuration['ws']['amazon']['tag']='" . $booklibrary_configuration['ws']['amazon']['tag'] . "';\n";
        $settings.= "\$booklibrary_configuration['ws']['amazon']['devtag']= '" . $booklibrary_configuration['ws']['amazon']['devtag'] . "';\n";
        $settings.= "\$booklibrary_configuration['ws']['amazon']['secret_key']= '" . $booklibrary_configuration['ws']['amazon']['secret_key'] . "';\n";
        $settings.= "// auto increment for bookid, if 1 - can't add random bookid \n";
        $settings.= "\$booklibrary_configuration['bookid']['auto-increment']['boolean']='" . $booklibrary_configuration['bookid']['auto-increment']['boolean'] . "';\n";
        $settings.= "// fetch images settings\n";
        $settings.= "\$booklibrary_configuration['fetchImages']['boolean']='" . $booklibrary_configuration['fetchImages']['boolean'] . "';\n";
        $settings.= "\$booklibrary_configuration['fetchImages']['location']='" . $booklibrary_configuration['fetchImages']['location'] . "';\n";
        $settings.= "// review settings\n";
        $settings.= "\$booklibrary_configuration['reviews']['show']='" . $booklibrary_configuration['reviews']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['reviews']['registrationlevel']='" . $booklibrary_configuration['reviews']['registrationlevel'] . "';\n";
        $settings.= "// publish added book\n";
        $settings.= "\$booklibrary_configuration['publish_on_add']['show']='" . $booklibrary_configuration['publish_on_add']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['publish_on_add']['registrationlevel']='" . $booklibrary_configuration['publish_on_add']['registrationlevel'] . "';\n";
        $settings.= "\$booklibrary_configuration['litpage']['show']='" . $booklibrary_configuration['litpage']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['litpage']['registrationlevel']='" . $booklibrary_configuration['litpage']['registrationlevel'] . "';\n";
        $settings.= "// lend settings\n";
        $settings.= "\$booklibrary_configuration['lendstatus']['show']='" . $booklibrary_configuration['lendstatus']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['lendrequest']['registrationlevel']='" . $booklibrary_configuration['lendrequest']['registrationlevel'] . "';\n";
        $settings.= "// ebook settings\n";
        $settings.= "\$booklibrary_configuration['ebooks']['allow']='" . $booklibrary_configuration['ebooks']['allow'] . "';\n";
        $settings.= "\$booklibrary_configuration['ebooks']['show']='" . $booklibrary_configuration['ebooks']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['ebooks']['registrationlevel']='" . $booklibrary_configuration['ebooks']['registrationlevel'] . "';\n";
        $settings.= "\$booklibrary_configuration['ebooks']['location']='" . $booklibrary_configuration['ebooks']['location'] . "';\n";
        $settings.= "// debuging\n";
        $settings.= "\$booklibrary_configuration['debug']='" . $booklibrary_configuration['debug'] . "';\n";
        $settings.= "\$booklibrary_configuration['page']['items']='" . $booklibrary_configuration['page']['items'] . "';\n";
        $settings.= "\$booklibrary_configuration['category']['default_sort']='" . $booklibrary_configuration['category']['default_sort'] . "';\n";
        $settings.= "// foto size\n";
        $settings.= "\$booklibrary_configuration['foto']['high']= '" . $booklibrary_configuration['foto']['high'] . "';\n";
        $settings.= "\$booklibrary_configuration['foto']['width']= '" . $booklibrary_configuration['foto']['width'] . "';\n";
        $settings.= "\$booklibrary_configuration['license']['show']='" . $booklibrary_configuration['license']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['license']['text']= '" . $booklibrary_configuration['license']['text'] . "';\n";
        // --------------------------community builder section------------------------
        $settings.= "// show cb_mybook\n";
        $settings.= "\$booklibrary_configuration['cb_mybook']['show']='" . $booklibrary_configuration['cb_mybook']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['cb_mybook']['registrationlevel']='" . $booklibrary_configuration['cb_mybook']['registrationlevel'] . "';\n";
        $settings.= "// show cb_edit\n";
        $settings.= "\$booklibrary_configuration['cb_edit']['show']='" . $booklibrary_configuration['cb_edit']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['cb_edit']['registrationlevel']='" . $booklibrary_configuration['cb_edit']['registrationlevel'] . "';\n";
        $settings.= "// show cb_rent\n";
        $settings.= "\$booklibrary_configuration['cb_rent']['show']='" . $booklibrary_configuration['cb_rent']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['cb_rent']['registrationlevel']='" . $booklibrary_configuration['cb_rent']['registrationlevel'] . "';\n";
        $settings.= "// show cb_history\n";
        $settings.= "\$booklibrary_configuration['cb_history']['show']='" . $booklibrary_configuration['cb_history']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['cb_history']['registrationlevel']='" . $booklibrary_configuration['cb_history']['registrationlevel'] . "';\n";
        // --------------------------end community builder section---------------------
        //**********************************   begin add button 'buy now'   ****************************************************
        $settings.= "// button '[ buy now ]'\n";
        $settings.= "\$booklibrary_configuration['buy_now']['show']='" . $booklibrary_configuration['buy_now']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['buy_now']['allow']['categories']='" . $booklibrary_configuration['buy_now']['allow']['categories'] . "';\n";
        $settings.= "\$booklibrary_configuration['addbook_button']['show']='" . $booklibrary_configuration['addbook_button']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['addbook_button']['allow']['categories']='" . $booklibrary_configuration['addbook_button']['allow']['categories'] . "';\n";
        $settings.= "\$booklibrary_configuration['addbook_button']['allow']['registrationlevel']='" . $booklibrary_configuration['addbook_button']['allow']['registrationlevel'] . "';\n";
        //**********************************   end add button 'buy now'   ******************************************************
        //**********************************   begin add button 'buy now vm'   ****************************************************
        $settings.= "\$booklibrary_configuration['update']='" . $booklibrary_configuration['update'] . "';\n";
        //**********************************   end add button 'buy now vm '   ******************************************************
        //**********************************   begin add button 'addtocart'   ****************************************************
        
        //**********************************   end add button 'addtocart '   ******************************************************
        //********************************** begin show approve_on_add     ****************************
        $settings.= "\$booklibrary_configuration['approve_on_add']['show']='" . $booklibrary_configuration['approve_on_add']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['approve_on_add']['registrationlevel']='" . $booklibrary_configuration['approve_on_add']['registrationlevel'] . "';\n";
        //********************* end show approve_on_add     ******************************************
        //*************************   begin add for Manager Suggestion: button 'Suggest a book'   ******************************

        //*****   end add for Manager Suggestion: button 'Suggest a book'  ***********
        //*************************   begin add for Manager Suggestion: button 'Suggest a book'   ******************************
        $settings.= "// button '[ my_books_button ]'\n";
        $settings.= "\$booklibrary_configuration['my_books_button']['show']='" . $booklibrary_configuration['my_books_button']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['my_books_button']['registrationlevel']='" . $booklibrary_configuration['my_books_button']['registrationlevel'] . "';\n";
        //*****   end add for Manager Suggestion: button 'Suggest a book'  ***********
        //*************************   begin add for Advance search  ******************************
        $settings.= "// Advance search \n";
        $settings.= "\$booklibrary_configuration['advsearch']['show']='" . $booklibrary_configuration['advsearch']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['advsearch']['registrationlevel']='" . $booklibrary_configuration['advsearch']['registrationlevel'] . "';\n";
        $settings.= "\$booklibrary_configuration['search_field']['show']='" . $booklibrary_configuration['search_field']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['search_field']['registrationlevel']='" . $booklibrary_configuration['search_field']['registrationlevel'] . "';\n";
        //*****   end add for Advance search  ***********
        //*************************   begin add for merge description  ******************************
        $settings.= "//merge description \n";
        $settings.= "\$booklibrary_configuration['merge_description']['use']='" . $booklibrary_configuration['merge_description']['use'] . "';\n";
        $settings.= "\$booklibrary_configuration['merge_description']['registrationlevel']='" . $booklibrary_configuration['merge_description']['registrationlevel'] . "';\n";
        //*****   end add for merge description'  ***********
        //
        // *****  RSS *********
        $settings.= "\$booklibrary_configuration['rss']['show']='" . $booklibrary_configuration['rss']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['rss']['registrationlevel']='" . $booklibrary_configuration['rss']['registrationlevel'] . "';\n";
        // *****  RSS *********
        //
        // *****  Owners list *********
        $settings.= "\$booklibrary_configuration['ownerslist']['show']='" . $booklibrary_configuration['ownerslist']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['ownerslist']['registrationlevel']='" . $booklibrary_configuration['ownerslist']['registrationlevel'] . "';\n";
        // *****  END Owners list *********
        // *****  PRINT VIEW *********
        $settings.= "\$booklibrary_configuration['print_view']['show']='" . $booklibrary_configuration['print_view']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['print_view']['registrationlevel']='" . $booklibrary_configuration['print_view']['registrationlevel'] . "';\n";
        // *****  PRINT VIEW *********
        // *****  PRINT PDF *********
        $settings.= "\$booklibrary_configuration['print_pdf']['show']='" . $booklibrary_configuration['print_pdf']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['print_pdf']['registrationlevel']='" . $booklibrary_configuration['print_pdf']['registrationlevel'] . "';\n";
        // *****  PRINT PDF *********
        // *****  MAIL TO *********
        $settings.= "\$booklibrary_configuration['mail_to']['show']='" . $booklibrary_configuration['mail_to']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['mail_to']['registrationlevel']='" . $booklibrary_configuration['mail_to']['registrationlevel'] . "';\n";
        // *****  MAIL TO *********
        //
        //*************************   begin add send mail for admin  ************
        $settings.= "// send email for admin\n";
        $settings.= "\$booklibrary_configuration['review_email']['address']='" . $booklibrary_configuration['review_email']['address'] . "';\n";
        $settings.= "\$booklibrary_configuration['review_added_email']['show']='" . $booklibrary_configuration['review_added_email']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['review_added_email']['registrationlevel']='" . $booklibrary_configuration['review_added_email']['registrationlevel'] . "';\n";
        $settings.= "\$booklibrary_configuration['suggest_email']['address']='" . $booklibrary_configuration['suggest_email']['address'] . "';\n";
        $settings.= "\$booklibrary_configuration['suggest_added_email']['show']='" . $booklibrary_configuration['suggest_added_email']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['suggest_added_email']['registrationlevel']='" . $booklibrary_configuration['suggest_added_email']['registrationlevel'] . "';\n";
        $settings.= "\$booklibrary_configuration['lendrequest_email']['address']='" . $booklibrary_configuration['lendrequest_email']['address'] . "';\n";
        $settings.= "\$booklibrary_configuration['lendrequest_email']['show']='" . $booklibrary_configuration['lendrequest_email']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['lendrequest_email']['registrationlevel']='" . $booklibrary_configuration['lendrequest_email']['registrationlevel'] . "';\n";
        $settings.= "\$booklibrary_configuration['addbook_email']['address']='" . $booklibrary_configuration['addbook_email']['address'] . "';\n";
        $settings.= "\$booklibrary_configuration['addbook_email']['show']='" . $booklibrary_configuration['addbook_email']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['addbook_email']['registrationlevel']='" . $booklibrary_configuration['addbook_email']['registrationlevel'] . "';\n";
        //*************************   end add send mail for admin   *************
        //add for show in category picture
        $settings.= "// show in category picture\n";
        $settings.= "\$booklibrary_configuration['cat_pic']['show']='" . $booklibrary_configuration['cat_pic']['show'] . "';\n";
        //******* Rent Request form******
        $settings.= "\$booklibrary_configuration['lend_answer']='" . $booklibrary_configuration['lend_answer'] . "';\n";
        $settings.= "\$booklibrary_configuration['lend_form']='" . $booklibrary_configuration['lend_form'] . "';\n";
        //******* Buy Request form******
        //add for show subcategory
        $settings.= "// show subcategory\n";
        $settings.= "\$booklibrary_configuration['subcategory']['show']='" . $booklibrary_configuration['subcategory']['show'] . "';\n";
        //---------------------------------
        $settings.= "//all_category \n";
        $settings.= "\$booklibrary_configuration['all_categories']='" . $booklibrary_configuration['all_categories'] . "';\n";
        //--------------------------------
        $settings.= "//all_category \n";
        $settings.= "\$booklibrary_configuration['view_book']='" . $booklibrary_configuration['view_book'] . "';\n";
        //---------------------
        $settings.= "//search_lay \n";
        $settings.= "\$booklibrary_configuration['search_lay']='" . $booklibrary_configuration['search_lay'] . "';\n";
        //--------------------
        $settings.= "//view type \n";
        $settings.= "\$booklibrary_configuration['view_type']='" . $booklibrary_configuration['view_type'] . "';\n";
        //--------------------
        $settings.= "//books \n";
        $settings.= "\$booklibrary_configuration['books']='" . $booklibrary_configuration['books'] . "';\n";
        //--------------------
        $settings.= "//ownerslist_page \n";
        $settings.= "\$booklibrary_configuration['ownerslist_page']='" . $booklibrary_configuration['ownerslist_page'] . "';\n";
        ///////////////////////////////////////////////////////ANTON CODE//////////////////////////////////////////
        /////////////Proxy Relase
        $settings.= "\$booklibrary_configuration['proxy_server']['address']='" . $booklibrary_configuration['proxy_server']['address'] . "';\n";
        $settings.= "\$booklibrary_configuration['port_proxy_server']['address']='" . $booklibrary_configuration['port_proxy_server']['address'] . "';\n";
        $settings.= "\$booklibrary_configuration['login_proxy_server']['address']='" . $booklibrary_configuration['login_proxy_server']['address'] . "';\n";
        $settings.= "\$booklibrary_configuration['password_proxy_server']['address']='" . $booklibrary_configuration['password_proxy_server']['address'] . "';\n";
        // Virtuemart

        //**********Denis
        $settings.= "\$booklibrary_configuration['owner']['show']='" . $booklibrary_configuration['owner']['show'] . "';\n";
        //**********Denis
        $settings.= "\$booklibrary_configuration['lend_before_end_notify']='" . $booklibrary_configuration['lend_before_end_notify'] . "';\n";
        $settings.= "\$booklibrary_configuration['lend_before_end_notify_days']='" . $booklibrary_configuration['lend_before_end_notify_days'] . "';\n";
        $settings.= "\$booklibrary_configuration['lend_before_end_notify_email']='" . $booklibrary_configuration['lend_before_end_notify_email'] . "';\n";
        $settings.= "\$booklibrary_configuration['price_format']='" . $booklibrary_configuration['price_format'] . "';\n";
        $settings.= "// 1 - affter 0 - beffore\n";
        $settings.= "\$booklibrary_configuration['price_unit_show']='" . $booklibrary_configuration['price_unit_show'] . "';\n";
        $settings.= "\$booklibrary_configuration['date_format']='" . $booklibrary_configuration['date_format'] . "';\n";
        $settings.= "\$booklibrary_configuration['datetime_format']='" . $booklibrary_configuration['datetime_format'] . "';\n";
        $settings.= "\$booklibrary_configuration['allowed_exts']='" . $booklibrary_configuration['allowed_exts'] . "';\n";
        $settings.= "\$booklibrary_configuration['allowed_exts_img']='" . $booklibrary_configuration['allowed_exts_img'] . "';\n";
        $settings.= "\$booklibrary_configuration['approve_review']['show']='" . $booklibrary_configuration['approve_review']['show'] . "';\n";
        $settings.= "\$booklibrary_configuration['approve_review']['registrationlevel']='" . $booklibrary_configuration['approve_review']['registrationlevel'] . "';\n";
        // Write out new initialization file

        $fd = fopen("./components/com_booklibrary/admin.booklibrary.class.conf.php", "w") or die("Cannot create configuration file.");
        fwrite($fd, $settings);
        fclose($fd);
    }
    /**
     * Rating Array
     * @return array an Array containing the information of all Rating
     * possibilities
     */
    static function getRatingArray() {
        $i = 0;
        $retVal = array();
        while ($i < 5) {
            //erster teil x,0
            $tmp = $i * 2;
            array_push($retVal, array($tmp, $i . ",0"));
            //zweiter teil x,5
            $tmp++;
            array_push($retVal, array($tmp, $i . ",5"));
            $i++;
        }
        array_push($retVal, array(10, "5,0"));
        return $retVal;
    }
    /**
     * Language Array - defined in the language files!
     * @return array an Array containing the information of all Language
     * possibilities
     */
    static function getLanguageArray() {
        $retVal = array();
        array_push($retVal, array("Not specified", _BOOKLIBRARY_LANGUAGE_NOT_USED));
        array_push($retVal, array("English", _BOOKLIBRARY_LANGUAGE_ENG));
        array_push($retVal, array("Dutch", _BOOKLIBRARY_LANGUAGE_DUT));
        array_push($retVal, array("Italian", _BOOKLIBRARY_LANGUAGE_ITA));
        array_push($retVal, array("French", _BOOKLIBRARY_LANGUAGE_FRE));
        array_push($retVal, array("German", _BOOKLIBRARY_LANGUAGE_GER));
        array_push($retVal, array("Persian", _BOOKLIBRARY_LANGUAGE_FA));
        array_push($retVal, array("Portuguese", _BOOKLIBRARY_LANGUAGE_PR));
        array_push($retVal, array("Serbian", _BOOKLIBRARY_LANGUAGE_SRP));
        array_push($retVal, array("Spanish", _BOOKLIBRARY_LANGUAGE_SPA));
        array_push($retVal, array("Russian", _BOOKLIBRARY_LANGUAGE_RUS));
        return $retVal;
    }
    /**
     * fetches the information from the imageURL field of the book and stores
     * the book with the ISBN number in the defined folder - then overwrites
     * the information in the imageURL field so that it points to the file
     * downloaded
     * @param mosBooklibrary store the book with all necessary information.
     * @return null if everything is OK, else return error string
     */
    static function storeImageFile(&$book, $picture) {
        global $mosConfig_live_site, $mosConfig_absolute_path, $booklibrary_configuration;
        $old_pic = $book->imageURL;
        //set path for local host images files
        $is_local_url = false;
        if (substr($old_pic, 0, 4) != "http") {
            $old_pic = $mosConfig_live_site . '/' . $old_pic;
            $is_local_url = true;
        }
        if ($picture != null) {
            $expl = explode('.', $picture['name']);
            $ext = $expl[count($expl) - 1];
            $rnd = substr(md5(time()), -8);
            $new_pic = $book->isbn . '_' . $rnd . '.' . $ext;
            //            $new_pic = substr($book->isbn . strrchr($picture['name'], "."), 1);
            if (!move_uploaded_file($picture['tmp_name'], $mosConfig_absolute_path . $booklibrary_configuration['fetchImages']['location'] . $new_pic)) {
                return "Error moving File!";
            } else {
                $book->imageURL = $booklibrary_configuration['fetchImages']['location'] . $new_pic;
                return null;
            }
        } elseif ($is_local_url) {
            //for local images - do only check
            if (!($ch = curl_init($old_pic))) return "Bad path to image file: $old_pic";
            curl_setopt($ch, CURLOPT_HEADER, 0);
            curl_setopt($ch, CURLOPT_FAILONERROR, 1);
            curl_exec($ch);
            $intReturnCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            curl_close($ch);
            if ($intReturnCode != 200) {
                return "Bad path image file";
            }
        } elseif (!$is_local_url && strlen(trim($old_pic)) > 0) {
            $expl = explode('.', $old_pic);
            $ext = $expl[count($expl) - 1];
            $rnd = substr(md5(time()), -8);
            $new_pic = $book->isbn . '_' . $rnd . '.' . $ext;
            //            $new_pic = substr($book->isbn . strrchr($book->imageURL, "."), 1);
            if (strrchr($new_pic, "/")) return "Bad path to image file: $book->imageURL";
            if (!($ch = curl_init($old_pic))) return "Bad path to image file: $old_pic";
            if ($fp = fopen($mosConfig_absolute_path . $booklibrary_configuration['fetchImages']['location'] . $new_pic, "w")) {
                curl_setopt($ch, CURLOPT_FILE, $fp);
                curl_setopt($ch, CURLOPT_HEADER, 0);
                curl_setopt($ch, CURLOPT_FAILONERROR, 1);
                curl_exec($ch);
                $intReturnCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
                curl_close($ch);
                fclose($fp);
                if ($intReturnCode != 200) {
                    unlink($mosConfig_absolute_path . $booklibrary_configuration['fetchImages']['location'] . $new_pic);
                    return "Bad path image file";
                }
            } else {
                return "Folder" . $booklibrary_configuration['fetchImages']['location'] . "dont exist";
            }
        } else {
            return "Bad path or access deny to save image file";
        }
    }
}